@startuml
left to right direction

actor Henviser
actor Visitator

usecase "1.2 Tilknytte klinisk\ndokumentation" as UC12
usecase "2.1 Modtage og\nkvittere" as UC21

Henviser --> UC12
Visitator --> UC21

UC12 --> UC21

@enduml