@startuml

 title Henvisning ID=1-version=01 - Opret henvisning
 participant Henviser
 participant Visitator

Henviser -> Visitator : Henvisning ID=1-version=01

@enduml

newpage

@startuml

 title Henvisning ID=1-version=02 - Supplerende dokumentation
 participant Henviser
 participant Visitator

Henviser -> Visitator : Henvisning ID=1-version=02

@enduml

newpage

@startuml

 title Henvisning ID=1-version=03 - Anmodning om supplerende oplysninger
 participant Henviser
 participant Visitator

Visitator -> Henviser : Henvisning ID=1-version=03

@enduml

newpage

@startuml

 title Henvisning ID=1-version=04 - Besvarelse af anmodning
 participant Henviser
 participant Visitator

Henviser -> Visitator : Henvisning ID=1-version=04

@enduml

newpage

@startuml

 title Henvisning ID=1-version=05 - Accept af henvisning
 participant Henviser
 participant Visitator

Visitator -> Henviser : Henvisning ID=1-version=05

@enduml

newpage

@startuml

 title Henvisning ID=1-version=06 - Booking gennemført
 participant Henviser
 participant Visitator

Visitator -> Henviser : Henvisning ID=1-version=06

@enduml

newpage

@startuml

 title Henvisning ID=1-version=07 - Afvisning
 participant Henviser
 participant Visitator

Visitator -> Henviser : Henvisning ID=1-version=07

@enduml

newpage

@startuml

 title Henvisning ID=1-version=08 - Videresendelse
 participant Henviser
 participant Visitator

Visitator -> Henviser : Henvisning ID=1-version=08

@enduml

newpage

@startuml

 title Henvisning ID=1-version=09 - Statusopdatering
 participant Henviser
 participant Visitator

Visitator -> Henviser : Henvisning ID=1-version=09

@enduml

newpage

@startuml

 title Henvisning ID=1-version=10 - Faglig dialog
 participant Henviser
 participant Visitator

loop indtil afklaring
Visitator -> Henviser : Dialog

Henviser -> Visitator : Dialog svar

end
@enduml

newpage

@startuml

 title Henvisning ID=1-version=11 - Alternativ visitation
 participant Henviser
 participant Visitator

Visitator -> Henviser : Alternativ visitation

Henviser -> Visitator : Accept/afvis

@enduml

newpage

@startuml

 title Henvisning ID=1-version=12 - Korrektion
 participant Henviser
 participant Visitator

Visitator -> Henviser : Korrektionsanmodning

Henviser -> Visitator : Korrigeret henvisning

@enduml